blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discussions
    url: https://github.com/LambdaTest/testMuBrowser/discussions
    about: Ask questions and discuss ideas
  - name: ğŸ“– Documentation
    url: https://github.com/LambdaTest/testMuBrowser/tree/main/docs
    about: Read the documentation
  - name: ğŸŒ LambdaTest Community
    url: https://community.lambdatest.com/
    about: Join the LambdaTest community
